---
# tasks file for ec2-launch

- name: "launching ec2 instances..."
  ec2:
          image: "{{ image }}"
          instance_type: "{{ instance_type }}"
          region: "{{ region }}"
          key_name: "{{ key }}"
          wait: yes
          count: 1
          state: present
          vpc_subnet_id: "{{ vpc_subnet_id }}"
          group_id: "{{ security_group_id }}"
          aws_access_key: "{{ akey }}"
          aws_secret_key: "{{ skey }}"
          instance_tags:
                  Name: "{{ item }}"
  loop: "{{ OS_Names }}"

