---
# tasks file for kube_slave
- name: "Installing docker and iproute-tc"
  package:
     name:
         - docker
         - iproute-tc
     state: present

- name: "Configuring the Yum repo for kubernetes"
  yum_repository:
     name: kubernetes
     description: Yum for k8s
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
     enabled: yes
     gpgcheck: yes
     repo_gpgcheck: yes
     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: "Installing kubeadm,kubelet kubectl program"
  yum:
     name:
        - kubelet
        - kubectl
        - kubeadm
     state: present
     
- name: "Enabling the docker and kubenetes"
  service:
     name: "{{ item }}"
     state: started
     enabled: yes
  loop:
        - kubelet
        - docker
        
- name: "Pulling the config images"
  shell: kubeadm config images pull

- name: "Confuring the docker daemon.json file"
  copy:
     dest: /etc/docker/daemon.json
     src: daemon.json
     
- name: "Restarting the docker service"
  service:
     name: docker
     state: restarted
     
- name: "Configuring the Ip tables and refreshing sysctl"
  copy:
     dest: /etc/sysctl.d/iptables-1.conf
     src: iptables-1.conf
     
- name: "systemctl"
  shell: "sysctl --system"

- name: Copy the join command to server location
  copy:
     src: /etc/ansible/roles/join-command
     dest: /tmp/join-command.sh
     mode: +x

- name: join command
  shell: "sh /tmp/join-command.sh"
